version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo apt-get -y install pandoc
      - run: sudo pip install pypandoc boto3 sly
      - run: python dynamodb_ce/tests/runtest.py
      - run: python setup.py sdist bdist_wheel
      - persist_to_workspace:
          root: dist
          paths:
            - dynamodb-ce*
  upload:
    docker:
      - image: circleci/python:3.7
    steps:
      - run: sudo pip install twine
      - attach_workspace:
          at: dist
      - run: twine upload dist/*
workflows:
  version: 2
  build-and-upload:
    jobs:
      - build
      - upload:
          context: pypi
          filters:
            branches:
              only:
                - unit_tests
          requires:
            - build
